[package]
name = "vote"
version = "1.0.0"
authors = []
edition = "2021"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"

[[bin]]
name = "vote"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release] #reduces Wasm size